export default function ProductPreview() {
  return (
    <section id="developers" className="py-24 bg-slate-50 border-t border-slate-100">
      <div className="max-w-6xl mx-auto px-6">
        <div className="flex flex-col lg:flex-row items-center gap-16">
          <div className="reveal-text flex-1 w-full lg:w-1/2">
            <div className="bg-white rounded-xl shadow-xl shadow-slate-200/60 border border-slate-200 overflow-hidden">
              <div className="flex items-center justify-between px-4 py-3 border-b border-slate-100 bg-slate-50/50">
                <div className="flex gap-1.5">
                  <div className="w-3 h-3 rounded-full bg-slate-200" />
                  <div className="w-3 h-3 rounded-full bg-slate-200" />
                </div>
                <span className="text-xs font-mono text-slate-400">
                  Checkout.tsx
                </span>
              </div>
              <div className="p-6 font-mono text-sm leading-relaxed overflow-x-auto">
                <div className="text-slate-400 mb-4">// 1. Import the hook</div>
                <div className="text-slate-800 inline">import</div>{" "}
                <span className="text-indigo-600">{"{ useFeature }"}</span>{" "}
                <div className="text-slate-800 inline">from</div>{" "}
                <span className="text-emerald-600">'@featureflow/react'</span>;
                <br />
                <br />
                <div className="text-purple-600 inline">export function</div>{" "}
                <span className="text-slate-900">CheckoutPage</span>() {"{"}
                <br />
                &nbsp;&nbsp;
                <div className="text-slate-400 inline">
                  // 2. Check flag status
                </div>
                <br />
                &nbsp;&nbsp;
                <div className="text-purple-600 inline">const</div> isNewFlow ={" "}
                <span className="text-indigo-600">useFeature</span>(
                <span className="text-emerald-600">'new-checkout'</span>);
                <br />
                <br />
                &nbsp;&nbsp;
                <div className="text-purple-600 inline">return</div> (
                <br />
                &nbsp;&nbsp;&nbsp;&nbsp;isNewFlow ?{" "}
                <span className="text-indigo-600">&lt;NewCheckout /&gt;</span> :{" "}
                <span className="text-slate-500">&lt;LegacyCheckout /&gt;</span>
                <br />
                &nbsp;&nbsp;);
                <br />
                {"}"}
              </div>
            </div>
          </div>

          <div className="reveal-text stagger-1 flex-1 space-y-8">
            <h2 className="text-3xl font-semibold text-slate-900 tracking-tight">
              Designed for developers.
            </h2>
            <p className="text-slate-500 text-lg leading-relaxed">
              Integrate in minutes with typed SDKs for React, Node, Python, and
              Go. We handle the caching, evaluations, and updates so you
              don&apos;t have to.
            </p>

            <ul className="space-y-4">
              <li className="flex items-start gap-3">
                <div className="mt-1 text-indigo-600">
                  <svg
                    aria-hidden
                    width="20"
                    height="20"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                  >
                    <path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2Zm-1 14-4-4 1.4-1.4L11 13.2l5.6-5.6L18 9Z" />
                  </svg>
                </div>
                <div>
                  <h4 className="text-slate-900 font-medium text-sm">
                    Type-safe SDKs
                  </h4>
                  <p className="text-slate-500 text-xs mt-1">
                    Autogenerated types based on your flags.
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <div className="mt-1 text-indigo-600">
                  <svg
                    aria-hidden
                    width="20"
                    height="20"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                  >
                    <path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2Zm-1 14-4-4 1.4-1.4L11 13.2l5.6-5.6L18 9Z" />
                  </svg>
                </div>
                <div>
                  <h4 className="text-slate-900 font-medium text-sm">
                    Local Fallbacks
                  </h4>
                  <p className="text-slate-500 text-xs mt-1">
                    Zero latency default values if connection drops.
                  </p>
                </div>
              </li>
              <li className="flex items-start gap-3">
                <div className="mt-1 text-indigo-600">
                  <svg
                    aria-hidden
                    width="20"
                    height="20"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                  >
                    <path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2Zm-1 14-4-4 1.4-1.4L11 13.2l5.6-5.6L18 9Z" />
                  </svg>
                </div>
                <div>
                  <h4 className="text-slate-900 font-medium text-sm">
                    Real-time Updates
                  </h4>
                  <p className="text-slate-500 text-xs mt-1">
                    Flag changes propagate globally in &lt;50ms.
                  </p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}
